name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Make a dummy change
        run: |
          echo "# Último commit automático: $(date)" >> daily_commit_log.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add daily_commit_log.md
          git commit -m "Commit automático: $(date)"
          git push
